-- 회원정보 테이블 생성
CREATE TABLE USER (
     USERNAME VARCHAR(20),
     PASSWORD VARCHAR(500),
     NICK_NAME VARCHAR(20),
     IS_ACCOUNT_NON_EXPIRED BOOLEAN,
     IS_ACCOUNT_NON_LOCKED BOOLEAN,
     IS_CREDENTIALS_NON_EXPIRED BOOLEAN,
     IS_ENABLED BOOLEAN
);

-- 회원 권한 테이블 생성
CREATE TABLE AUTHORITY (
    USER_NAME VARCHAR(20) NOT NULL,
    AUTHORITY_NAME VARCHAR(20) NOT NULL
);

-- 게시판 테이블 생성
CREATE TABLE BOARD(
	BOARD_ID INTEGER(9) PRIMARY KEY AUTO_INCREMENT NOT NULL,
	USER_ID VARCHAR(10) NOT NULL,
	SUBJECT VARCHAR(30) NOT NULL,
	CONTENTS TEXT(1000),
	REG_DATE TIMESTAMP NOT NULL,
	LAST_MD_DATE TIMESTAMP NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USER(USERNAME)
	);
